# Местонахождение
homeassistant:
  name: My Smart Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 198
  unit_system: metric
  time_zone: Europe/Kiev
  country: UA
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages

automation: !include automations.yaml
script: !include script.yaml
scene: !include scene.yaml
sensor: !include sensor.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Голосовая панель
tts:
  - platform: google_translate
    language: "uk"

# lovelace
lovelace:
  mode: yaml
  resources: 
    - url: /hacsfiles/honeycomb-menu/honeycomb-menu.js
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/ha-floorplan/floorplan.js
      type: module
    - url: /hacsfiles/floor3d-card/floor3d-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/slider-button-card/slider-button-card.js
      type: module
    - url: /hacsfiles/button-text-card/button-text-card.js
      type: module
    - url: /hacsfiles/honeycomb-menu/honeycomb-menu.js
      type: module
    - url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/flex-table-card/flex-table-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/radial-menu/radial-menu.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/lovelace-digital-clock/digital-clock.js
      type: module
    - url: /hacsfiles/analogclock/analogclock.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/surveillance-card/surveillance-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/lightalarm-card/lightalarm-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module
    - url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
      type: module
    - url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js
      type: module
    - url: /hacsfiles/custom-brand-icons/custom-brand-icons.js
      type: module
    - url: /hacsfiles/hass-blind-card/hass-blind-card.js
      type: module
    - url: /hacsfiles/lovelace-vertical-slider-cover-card/vertical-slider-cover-card.js
      type: module

# Добавьте больше информационных панелей
  dashboards:
    lovelace-tablet: # Должен содержать дефис (-)
      mode: yaml
      filename: ui-планшет.yaml
      title: Планшет
      icon: mdi:tablet-dashboard
#      show_in_sidebar: false                     # после настройки вкл. (не отображение на боковой панели)
      require_admin: false
    lovelace-phone: # Должен содержать дефис (-)
      mode: yaml
      filename: ui-телефон.yaml
      title: Телефон
      icon: mdi:cellphone-text
#      show_in_sidebar: false                     # после настройки вкл. (не отображение на боковой панели)
      require_admin: false

# Роутер ping устройств
device_tracker:
  - platform: xiaomi
    host: !secret xiaomi_router_ip
    password: !secret xiaomi_router_password
  - platform: ping
    scan_interval: 30
    count: 3
    consider_home: 92
    hosts:
      ping_cepera: !secret cepera_ip
      ping_nadya: !secret nadya_ip


# Платформа телеграмм бота
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key_bot
    allowed_chat_ids:
      - !secret telegram_ID_Cepera
      - !secret telegram_ID_Nadya
      - !secret telegram_ID_group
      - !secret telegram_ID_group_Trevoga

# Платформа телеграмм уведомлений
notify:
  - name: Telegram_Cepera
    platform: telegram
    chat_id: !secret telegram_ID_Cepera
  - name: Telegram_Nadya
    platform: telegram
    chat_id: !secret telegram_ID_Nadya
  - name: Telegram_Group
    platform: telegram
    chat_id: !secret telegram_ID_group
  - name: Telegram_Air_Trevoga
    platform: telegram
    chat_id: !secret telegram_ID_group_Trevoga

media_player:
  - platform: mpd
    host: 0.0.0.0
    port: 6600

# Добавление Morpidy
panel_iframe:
  morpidy:
    title: 'Morpidy'
    icon: 'mdi:music-circle'
    url: 'http://192.168.31.100:6680/iris'
  
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: UA #optional, added in 3.6.24

# URL - media_extractor
media_extractor:

# Добавление xiaomi пылесоса
vacuum:
  - platform: xiaomi_vacuum
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    name: MiRobot_vacuum

# Добавление xiaomi Увлажнителя воздуха
fan:
  - platform: xiaomi_miio_airpurifier
    name: Humidifier_Xiaomi
    host: !secret humidifier_xiaomi_host
    token: !secret humidifier_xiaomi_token
    model: deerma.humidifier.jsq5

# pyscript
pyscript:
  allow_all_imports: true
  hass_is_global: true

# Вынос во внешние файлы
recorder: !include includes/recorder.yaml
group: !include includes/groups.yaml

# Темы
frontend:
  themes: !include_dir_merge_named themes
















