############################ Свайп для перелистования ########################################
swipe_nav:
  wrap: false
  animate: swipe
  prevent_default: true
  swipe_amount: 30
  
############################ Настройки Kioska ########################################
kiosk_mode:
#   non_admin_settings:
#     hide_menubutton: true 
#     hide_overflow: true 
#     # hide_header: true 
#     # ignore_entity_settings: t
    kiosk: true

############################ Картинка Фона ########################################
#background: "center / cover no-repeat fixed url('/local/background/1345362585-2296003-5.jpg')"

############################ Вкладки ########################################
views:
  - !include lovelace/ui-телефон/1_main.yaml
  - !include lovelace/ui-телефон/2_lights.yaml
  - !include lovelace/ui-телефон/3_switchs.yaml
  - !include lovelace/ui-телефон/4_blinds.yaml
  - !include lovelace/ui-телефон/5_media.yaml
  - !include lovelace/ui-телефон/6_camers.yaml
 
############################ Шаблоны ########################################
button_card_templates:


### Заголовок
  button_zagolovok:
    show_name: true
    aspect_ratio: 12/1                                   # соотношение высоты и ширины
    show_icon: false
    tap_action:
      action: none
    styles:
      name:
        - font-size: 20px                                # размер шрифта
#        - font-weight: 1000                             # толщина шрифта
#        - justify-self: start/end                       # расположение текста
      card:
        - box-shadow: '0px 0px 3px 3px yellow'             # ширина тени спрва/снизу/размытие рамки/толщина рамки/цвет
        - border-radius: 10px                            # радиус рамки
#        - color:   blue                                  # цвет шрифта
        - background-color: blue                   # цвет фона
#        - opacity: 0.3                            # прозрачность


### Датчики по умолчанию
  button_sensor:
    show_name: false
    size: 40px
    aspect_ratio: 3.9/1
    tap_action:
      action: none
    styles:
      card:
#        - box-shadow: '1px 1px 2px 1px #808080'
        - box-shadow: '1px 1px 2px 1px yellow'
        - border-radius: 2px
        - margin: 0px 0px 4px 0px                  
        - padding: 2%
      icon:
        - color: '#1872F2'
      grid:
        - grid-template-areas: '"i temp temp"'
        - grid-template-columns: 35px 1fr 1fr 
        - grid-template-rows: 1fr
      custom_fields:
        temp:
          - font-weight: 450
          - font-size: 16px
#          - justify-self: start
          - padding-left: 15px
    custom_fields:
      temp: |
        [[[
          var temp = entity.state;
          var temp_a = entity.attributes.unit_of_measurement;
          return temp + ' ' + temp_a;
        ]]]


##################################################################################################
##################################### Общий шаблон для комнат ####################################
##################################################################################################
  button_sensor_name:
    show_name: true
    size: 40px
    aspect_ratio: 3/1
    tap_action:
      action: none
    styles:
      name:
        - justify-self: end
        - align-self: end
        - padding: 3px 6px
        - font-size: 12px
      card:
#        - box-shadow: '1px 1px 2px 1px #808080'
        - box-shadow: '1px 1px 2px 1px yellow'
        - border-radius: 2px
        - margin: 0px 0px 4px 0px                  
        - padding: 2%
      icon:
        - color: '#1872F2'
      grid:
        - grid-template-areas: '"i temp temp"'
        - grid-template-columns: 35px 1fr 1fr 
        - grid-template-rows: 1fr
      custom_fields:
        temp:
          - font-weight: 450
          - font-size: 16px
          - justify-self: start
          - padding-left: 15px
    custom_fields:
      temp: |
        [[[
          var temp = entity.state;
          var temp_a = entity.attributes.unit_of_measurement;
          return temp + ' ' + temp_a;
        ]]]


##################################### Датчики Окон/Дверей ####################################
  button_sensor_door:
    show_last_changed: true
    show_name: true
    size: 40px
    aspect_ratio: 3/1
    tap_action:
      action: none
    styles:
      name:                                        # название датчика
        - justify-self: end
        - align-self: end
        - padding: 2px 3px                    # отступ от низа/отступ от правого края
        - font-size: 12px                    # размер шрифта
      card:
#        - box-shadow: '1px 1px 2px 1px #808080'
        - box-shadow: '1px 1px 2px 1px yellow'
        - border-radius: 2px
        - margin: 0px 0px 4px 0px                  
        - padding: 2%
      icon:
        - color: '#1872F2'
      grid:
        - grid-template-areas: '"i temp temp" "i l l" "i n n"'
        - grid-template-columns: 40px 1fr 1fr 
        - grid-template-rows: 1fr
      custom_fields:
        temp:                                        # значение датчика
          - font-weight: 450                         # толщина шрифта
          - font-size: 16px                          # размер шрифта
          - justify-self: start                      # расположение шрифта
          - padding-left: 3px                        # отступ от начала
      label:
#        - justify-self: 
        - font-size: 10px
        - color: '#6cace4'
    custom_fields:                                          
        temp: |
            [[[
              var temp = entity.state;
              if (temp == 'off') return 'Закрыто';
              if (temp == 'on') return 'Открыто';
            ]]]
    state:                                            # цвета каждого состояния датчиков
      - value: 'unavailable'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px #808080'
            - color: '#808080'
          icon:
            - color: '#808080'
      - value: 'off'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px yellow'
        #     - color: green
        #   icon:
        #     - color: orange
      - value: 'on'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px #5ff71d'
            - color: '#5ff71d'
          icon:
            - color: '#5ff71d'

##################################### Датчики Движения ####################################
  button_sensor_motion:
    show_last_changed: true
    show_name: true
    size: 40px
    aspect_ratio: 3/1
    tap_action:
      action: none
    styles:
      name:                                        # название датчика
        - justify-self: end
        - align-self: end
        - padding: 2px 3px
        - font-size: 12px
      card:
#        - box-shadow: '1px 1px 2px 1px #808080'
        - box-shadow: '1px 1px 2px 1px yellow'
        - border-radius: 2px
        - margin: 0px 0px 4px 0px                  
        - padding: 2%
      icon:
        - color: '#1872F2'
      grid:
        - grid-template-areas: '"i temp temp" "i l l" "i n n"'
        - grid-template-columns: 35px 1fr 1fr 
        - grid-template-rows: 1fr
      custom_fields:
        temp:                                        # значение датчика
          - font-weight: 450                         # толщина шрифта
          - font-size: 16px                          # размер шрифта
          - justify-self: start                      # расположение шрифта
          - padding-left: 3px                        # отступ от начала
      label:
#        - justify-self: 
        - font-size: 10px
        - color: '#6cace4'
    custom_fields:                                          
        temp: |
            [[[
              var temp = entity.state;
              if (temp == 'off') return 'Тишина';
              if (temp == 'on') return 'Движение';
            ]]]
    state:                                            # цвета каждого состояния датчиков
      - value: 'unavailable'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px #808080'
            - color: '#808080'
          icon:
            - color: '#808080'
      - value: 'off'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px yellow'
        #     - color: green
        #   icon:
        #     - color: orange
      - value: 'on'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px #5ff71d'
            - color: '#5ff71d'
          icon:
            - color: '#5ff71d'

##################################### Протечки ####################################
  button_sensor_Water_Leak:
    show_name: true
    size: 40px
    aspect_ratio: 3/1
    tap_action:
      action: none
    styles:
      name:                                        # название датчика
        - justify-self: end
        - align-self: end
        - padding: 2px 3px
        - font-size: 12px
      card:
#        - box-shadow: '1px 1px 2px 1px #808080'
        - box-shadow: '1px 1px 2px 1px yellow'
        - border-radius: 2px
        - margin: 0px 0px 4px 0px
        - padding: 2%
      icon:
        - color: '#1872F2'
      grid:
        - grid-template-areas: '"i temp temp" "i n n"'
        - grid-template-columns: 35px 1fr 1fr 
        - grid-template-rows: 1fr
      custom_fields:
        temp:                                        # значение датчика
          - font-weight: 450                         # толщина шрифта
          - font-size: 16px                          # размер шрифта
          - justify-self: start                      # расположение шрифта
          - padding-left: 15px                       # отступ от начала
    custom_fields:                                          
        temp: |
            [[[
              var temp = entity.state;
              if (temp == 'off') return 'Сухо';
              if (temp == 'on') return 'Протечки';
            ]]]
    state:                                            # цвета каждого состояния датчиков
      - value: 'unavailable'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px #808080'
            - color: '#808080'
          icon:
            - color: '#808080'
      - value: 'off'
        styles:
          card:
            - box-shadow: '1px 1px 1px 2px yellow'
        #     - color: green
        #   icon:
        #     - color: orange
      - value: 'on'
        styles:
          card:
            # - box-shadow: '1px 1px 1px 2px red'
            - color: red
            # - animation: blink 1s linear infinite
            - animation: flasher 1s linear infinite
          icon:
            - color: red
    extra_styles: |
      @keyframes flasher {
        50% { background: radial-gradient(rgb(0, 0, 0, 10%) 20%, rgb(255, 0, 0, 50%));
        box-shadow: 0px 0px 30px rgb(255, 0, 0, 100%);
        border: 5px solid rgb(200, 150, 150)
      }




#==============================================================================================================#
##################################################### Жалюзи ###################################################
#==============================================================================================================#

################################################## Гостиная #####################################################
  button_cover_purpur_full:
        show_name: true
        show_icon: true
        show_label: true
        tap_action:
          action: toggle
        styles:
          card:
            - height: 47px
            - width: 120px
            - border-radius: 3px
            - padding: 2%
          grid:
            - grid-template-areas: '"i temp temp" "i n n" "i n n"'
            - grid-template-columns: 35px
            - grid-template-rows: 1fr 4fr 2fr
          icon:
            - color: '#fa1478'
            - width: 60px
          label:
            - font-size: 8px
            - color: '#6cace4'
          name:
            - padding: 0px 3px
            - font-size: 16px
            - font-weight: bold
            - padding-left: 15px
          custom_fields:
            temp:                                        # значение датчика
              - font-weight: 180                         # толщина шрифта
              - font-size: 12px                          # размер шрифта
        custom_fields:
            temp: |
                [[[
                  var temp = entity.state;
                  if (temp == 'off') return 'Откр на';
                  if (temp == 'on') return 'Откр на';
                ]]]

  button_cover_purpur:
        show_name: true
        show_icon: true
        show_label: true
        aspect_ratio: 1/1
        tap_action:
          action: toggle
        styles:
          card:
            - border-radius: 3px
            - padding: 2%
          grid:
            - grid-template-areas: '"i i i" "temp temp temp" "n n n"'
            - grid-template-columns: 35px
            - grid-template-rows: 4fr 2fr 2fr
          icon:
            - color: '#fa1478'
            - width: 100px
          name:
            - padding: 0px 3px
            - font-size: 10px
            - font-weight: bold
#            - padding-left: 15px
          custom_fields:
            temp:                                        # значение датчика
              - font-weight: 100                         # толщина шрифта
              - font-size: 10px                          # размер шрифта
        custom_fields:
            temp: |
                [[[
                  var temp = entity.state;
                  if (temp == 'off') return 'Откр на';
                  if (temp == 'on') return 'Откр на';
                ]]]

################################################## Спальня #####################################################
  button_cover_blue_full:
        show_name: true
        show_icon: true
        show_label: true
        tap_action:
          action: toggle
        styles:
          card:
            - height: 47px
            - width: 120px
            - border-radius: 3px
            - padding: 2%
          grid:
            - grid-template-areas: '"i temp temp" "i n n" "i n n"'
            - grid-template-columns: 35px
            - grid-template-rows: 1fr 4fr 2fr
          icon:
            - color: '#265cff'
            - width: 60px
          label:
            - font-size: 8px
            - color: '#6cace4'
          name:
            - padding: 0px 3px
            - font-size: 16px
            - font-weight: bold
            - padding-left: 15px
          custom_fields:
            temp:                                        # значение датчика
              - font-weight: 180                         # толщина шрифта
              - font-size: 12px                          # размер шрифта
        custom_fields:
            temp: |
                [[[
                  var temp = entity.state;
                  if (temp == 'off') return 'Откр на';
                  if (temp == 'on') return 'Откр на';
                ]]]

  button_cover_blue:
        show_name: true
        show_icon: true
        show_label: true
        aspect_ratio: 1/1
        tap_action:
          action: toggle
        styles:
          card:
            - border-radius: 3px
            - padding: 2%
          grid:
            - grid-template-areas: '"i i i" "temp temp temp" "n n n"'
            - grid-template-columns: 35px
            - grid-template-rows: 4fr 2fr 2fr
          icon:
            - color: '#265cff'
            - width: 100px
          name:
            - padding: 0px 3px
            - font-size: 10px
            - font-weight: bold
#            - padding-left: 15px
          custom_fields:
            temp:                                        # значение датчика
              - font-weight: 100                         # толщина шрифта
              - font-size: 10px                          # размер шрифта
        custom_fields:
            temp: |
                [[[
                  var temp = entity.state;
                  if (temp == 'off') return 'Откр на';
                  if (temp == 'on') return 'Откр на';
                ]]]


################################################## Кухня #####################################################
  button_cover_green_full:
        show_name: true
        show_icon: true
        show_label: true
        tap_action:
          action: toggle
        styles:
          card:
            - height: 47px
            - width: 120px
            - border-radius: 3px
            - padding: 2%
          grid:
            - grid-template-areas: '"i temp temp" "i n n" "i n n"'
            - grid-template-columns: 35px
            - grid-template-rows: 1fr 4fr 2fr
          icon:
            - color: '#78fa14'
            - width: 60px
          label:
            - font-size: 8px
            - color: '#6cace4'
          name:
            - padding: 0px 3px
            - font-size: 16px
            - font-weight: bold
            - padding-left: 15px
          custom_fields:
            temp:                                        # значение датчика
              - font-weight: 180                         # толщина шрифта
              - font-size: 12px                          # размер шрифта
        custom_fields:
            temp: |
                [[[
                  var temp = entity.state;
                  if (temp == 'off') return 'Откр на';
                  if (temp == 'on') return 'Откр на';
                ]]]

  button_cover_green:
        show_name: true
        show_icon: true
        show_label: true
        aspect_ratio: 1/1
        tap_action:
          action: toggle
        styles:
          card:
            - border-radius: 3px
            - padding: 2%
          grid:
            - grid-template-areas: '"i i i" "temp temp temp" "n n n"'
            - grid-template-columns: 35px
            - grid-template-rows: 4fr 2fr 2fr
          icon:
            - color: '#78fa14'
            - width: 100px
          name:
            - padding: 0px 3px
            - font-size: 10px
            - font-weight: bold
#            - padding-left: 15px
          custom_fields:
            temp:                                        # значение датчика
              - font-weight: 100                         # толщина шрифта
              - font-size: 10px                          # размер шрифта
        custom_fields:
            temp: |
                [[[
                  var temp = entity.state;
                  if (temp == 'off') return 'Откр на';
                  if (temp == 'on') return 'Откр на';
                ]]]




































































































