esphome:
  name: d1-mini-6

esp8266:
  board: d1_mini

# Включить ведение журнала
logger:

# Активация Home Assistant API
api:
  encryption:
    key: "IypzdBCusXRaFKq5um2RH5jAoUsjlaDTKMp8="

ota:
    password: "7"

# wi-fi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Включить резервную точку доступа
  ap:
    ssid: "D1Mini-1"
    password: ""

captive_portal:

binary_sensor:

  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
    name: "Touch light"
    on_multi_click:
    ########################### single click
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_single
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_single
    ############################ double click
    - timing: 
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_double
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_double
    ############################ triple click
    - timing: 
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_triple
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_triple
    ####################################### hold button
    - timing: 
      - ON for 2s to 5s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_hold
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_hold




  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    id: raw_switch_state
    internal: true
    filters:
      - invert:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: bedside_button
              state: !lambda 'return "single";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: bedside_button
              state: !lambda 'return "double";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
          - text_sensor.template.publish:
              id: bedside_button
              state: !lambda 'return "triple";'
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: bedside_button
              state: !lambda 'return "hold";'

text_sensor:
  - platform: template
    name: "Bedside button"
    id: bedside_button
    icon: "mdi:toggle-switch"
    on_value:
      then:
        - if:
            condition:
              text_sensor.state:
                id: bedside_button
                state: ""
            else:
              - delay: 20ms
              - text_sensor.template.publish:
                  id: bedside_button
                  state: !lambda 'return "";'





















