esphome:
  name: esp32-ostrovok
  friendly_name: esp32-ostrovok

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Активация Home Assistant API
api:
  encryption:
    key: "zJrcw6F15j/23NmbRMo7VsJAIgpZ1pd+FMiNHPaI="

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Ostrovok Fallback Hotspot"
    password: "qKJjkkrKiUAh"

captive_portal:

# Интерфал сканирования
esp32_ble_tracker:

  #scan_parameters:
   # interval: 1100ms
   # window: 1100ms
  #  active: true

#bluetooth_proxy:
  #active: true

binary_sensor:

# Наличие BLE устройств в зоне видимости
  - platform: ble_presence
    mac_address: 
    name: "CeperA Mi Band"
    device_class: connectivity
  - platform: ble_presence
    mac_address: 
    name: "Nadya Mi Band"
    device_class: connectivity

# Добавление кнопок ttp223
  - platform: gpio
    pin: 
      number: GPIO27
    name: "Touch ble music"

  - platform: gpio
    pin: 
      number: GPIO26
    name: "Touch chainik"

# Кнопка Света
  - platform: gpio
    pin: 
      number: GPIO17
      mode: INPUT_PULLUP
    name: "Touch light"
    on_multi_click:
########################### single click
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_single
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_single
############################ double click
    - timing: 
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_double
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_double
############################ triple click
    - timing: 
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_triple
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_triple
####################################### hold button
    - timing: 
      - ON for 2s to 5s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light_button_hold
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light_button_hold

# Кнопка ленты подсветки
  - platform: gpio
    pin: 
      number: GPIO16
      mode: INPUT_PULLUP
    name: "Touch LED"
    on_multi_click:
########################### single click
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_led_button_single
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_led_button_single
############################ double click
    - timing: 
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_led_button_double
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_led_button_double
############################ triple click
    - timing: 
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_led_button_triple
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_led_button_triple
####################################### hold button
    - timing: 
      - ON for 2s to 5s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_led_button_hold
        - delay: 0.2s
        - homeassistant.service:
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_led_button_hold

# Добавление кнопки (в данном случаи нажатие на энкодер)
  - platform: gpio
    name: "Phone Encoder Button"
    id: phone_rotary_encoder_button
    pin: 
      number: GPIO19                              # key
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - sensor.rotary_encoder.set_value:
            id: phone_rotary_encoder
            value: 50

  - platform: gpio
    name: "Blinds Encoder Button"
    id: blinds_rotary_encoder_button
    pin: 
      number: GPIO21                             # key
      inverted: true
      mode: INPUT_PULLUP

    on_press:
      then:
        - sensor.rotary_encoder.set_value:
            id: blinds_rotary_encoder
            value: 0

interval:
  - interval: 1min
    then:
        - sensor.rotary_encoder.set_value:
            id: blinds_rotary_encoder
            value: 0

sensor:

# Добавление Энкодера
  - platform: rotary_encoder
    name: "Phone vol Rotary Encoder"
    id: phone_rotary_encoder
    pin_a: GPIO5                              # S2
    pin_b: GPIO18                             # S1
    resolution: 4                         # с каким шагом переключаеться энкодер
    min_value: 0
    max_value: 100

  - platform: rotary_encoder
    name: "Blinds Rotary Encoder"
    id: blinds_rotary_encoder
    pin_a: GPIO22                              # S2
    pin_b: GPIO23                             # S1
    min_value: -1
    max_value: 1

# Уровень сигнала обнаруженных устройств
  - platform: ble_rssi
    mac_address: 
    name: "Cepera signal Mi Band 4"
  - platform: ble_rssi
    mac_address: 
    name: "Nadya signal Mi Band 4"

  - platform: wifi_signal
    name: WiFi Signal blinds LR
    id: wifis_signal
    update_interval: 900s

text_sensor:
  - platform: wifi_info
    ssid:
      name: ESP Connected SSID

switch:
  - platform: gpio
    pin: GPIO32
    name: "relay ble music"
    id: relay1
    inverted: true

  - platform: gpio
    pin: GPIO33
    name: "relay charger phone"
    id: relay2
    inverted: true

  - platform: restart
    name: "Restart Ostrovok"









